# OutlawClans configuration
territory:
  price: 0
  radius: 75           # 150x150
  upgrade_radius_increase: 50
  world: "world"

building:
  spots: 6
  plot_size: 35
  edge_margin: 12
  paste_y_offset: 1     # +1 bloc
  sign_y_offset: 2
  sign_height_search: 5      # recherche vers le haut pour poser la pancarte sur la surface
  min_spacing: 40
  fence:
    enabled: true
    material: "OAK_FENCE"
    segment_length: 6
    gap_length: 6
    height: 1
    offset: 1
    y_offset: 1
  center_schematic:
    enabled: true
    file: "ClanCenter.schem"
    extra_delay_ticks: 40
    lectern_radius: 4

ui:
  show_duration_seconds: 30

roles:
  default: "recruit"
  defaults:
    officer:
      name: "&6Officier"
      permissions:
        - BUILD_TERRAIN
        - MANAGE_TERRAINS
        - ACCESS_FARM_CHEST
        - MANAGE_TREASURY
    member:
      name: "&aMembre"
      permissions:
        - BUILD_TERRAIN
        - ACCESS_FARM_CHEST
    recruit:
      name: "&7Recrue"
      permissions: []

economy:
  mode: "XP"            # XP ou ITEM
  item_type: "DIAMOND"
  amount_buttons: [16, 32, 64, 128]
  xp:
    create_clan_cost: 500
    territory_cost: 1500
    upgrade_cost: 2000
  item:
    create_clan_cost: 64
    territory_cost: 192
    upgrade_cost: 256

schematics:
  require_whitelist: true
  whitelist:
    - "ecosmp4.schem"
    - "ecosmp3.schem"
    - "ClanCenter.schem"

resource_farms:
  payout_interval_ticks: 18000   # 15 minutes
  chest_item:
    name: "&6Coffre de récolte - {type}"
    lore:
      - "&7Placez-le dans votre territoire pour relier {type}."
      - "&7Il recevra les ressources périodiquement."
  types:
    miner:
      name: "&eFerme Minier"
      icon: "IRON_PICKAXE"
      description:
        - "&7Mine automatique pour vos ressources métalliques."
      schematics:
        - "FermeMinier_T1.schem"
        - "FermeMinier_T2.schem"
      outputs:
        IRON_INGOT: 24
        RAW_GOLD: 12
        COAL: 32
    lumberjack:
      name: "&6Ferme Bûcheron"
      icon: "IRON_AXE"
      description:
        - "&7Abat périodiquement du bois raffiné."
      schematics:
        - "FermeBucheron_T1.schem"
      outputs:
        OAK_LOG: 32
        SPRUCE_LOG: 32
        STICK: 48
    farmer:
      name: "&aFerme Agricole"
      icon: "IRON_HOE"
      description:
        - "&7Culture automatisée pour nourrir le clan."
      schematics:
        - "FermeAgricole_T1.schem"
        - "FermeAgricole_T2.schem"
      outputs:
        WHEAT: 48
        POTATO: 48
        CARROT: 48

terraform:
  enabled: true
  full_territory: true
  surface_top_material: "GRASS_BLOCK"
  platform_per_plot: false
  thickness: 10
  material: "DIRT"
  clear_above: 24
  blocks_per_tick: 1500
  spawn_npc_delay_ticks: 120
  kill_entities: true

# Lissage des bords du territoire (évite le grand mur vertical)
feather:
  enabled: true
  width: 20                       # largeur de la zone de blend autour du 150x150
  top_material: "GRASS_BLOCK"
  foundation_material: "DIRT"
  extra_depth_below: 20           # remplit 20 blocs plus bas que l'épaisseur
  ignore_foliage: true            # calcule la hauteur naturelle en ignorant feuilles/troncs/décors
